"use client";

import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

export type AdminLang = "en" | "ru" | "uz";

const dict: Record<AdminLang, Record<string, string>> = {
  en: {
    "nav.dashboard": "Dashboard",
    "nav.orders": "Orders",
    "nav.products": "Products",
    "nav.categories": "Categories",
    "categories.nameEn": "Name (EN)",
    "categories.nameRu": "Name (RU)",
    "categories.nameUz": "Name (UZ)",
    "categories.slug": "Slug",
    "categories.slugHint": "URL-safe identifier, auto-generated",
    "categories.empty": "No categories yet",
    "nav.users": "Users",
    "nav.promoCodes": "Promo Codes",
    "nav.settings": "Settings",
    "nav.notifications": "Notifications",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.search": "Search...",
    "common.loading": "Loading...",
    "common.noData": "No data",
    "common.actions": "Actions",
    "common.view": "View",
    "auth.phone": "Phone",
    "users.noUsers": "No users found",
    "users.totalOrders": "Total orders",
    "users.totalSpent": "Total spent",
    "users.default": "Default",
    "users.notFound": "User not found",
    "users.backToList": "Back to users",
    "dashboard.live": "Live",
    "dashboard.offline": "Offline",
    "dashboard.orderId": "Order ID",
    "dashboard.customer": "Customer",
    "dashboard.total": "Total",
    "dashboard.revenue": "Revenue",
    "dashboard.orders": "Orders",
    "dashboard.items": "Items",
    "dashboard.profit": "Profit",
    "dashboard.share": "Share",
    "dashboard.uniqueBuyers": "unique buyers",
    "dashboard.itemsSold": "Items sold",
    "dashboard.groupByHour": "Grouped by hour",
    "dashboard.groupByDay": "Grouped by day",
    "dashboard.groupByMonth": "Grouped by month",
    "users.searchPlaceholder": "Search by name or phone",
    "users.joined": "Joined",
    "users.status": "Status",
    "users.role": "Role",
    "common.block": "Block",
    "common.unblock": "Unblock",
    "common.signOut": "Sign out",
    "auth.signIn": "Sign in",
    "auth.signInToAccount": "Sign in to your admin account",
    "products.title": "Products",
    "products.add": "Add Product",
    "products.name": "Name",
    "products.category": "Category",
    "products.type": "Type",
    "products.series": "Series",
    "products.variants": "Variants",
    "products.sku": "SKU",
    "products.flavor": "Flavor",
    "products.weight": "Net Weight",
    "products.price": "Price",
    "products.stock": "Stock",
    "products.costPrice": "Cost Price",
    "products.margin": "Margin",
    "products.info": "Product info",
    "products.addVariant": "Add variant",
    "products.saveProduct": "Save product",
    "products.saveVariant": "Save variant",
    "products.newVariant": "New variant",
    "products.noVariants": "No variants yet. Add at least one flavor/size.",
    "products.nameRequired": "Name is required",
    "products.categoryRequired": "Category is required",
    "products.skuPriceRequired": "SKU and Price are required",
    "common.select": "Select...",
    "products.image": "Image",
    "products.translations": "Translations",
    "products.flavorLabel": "Flavor Label",
    "products.typeName": "Type Name",
    "products.description": "Description",
    "products.ingredients": "Ingredients",
    "settings.title": "Settings",
    "settings.deliveryFee": "Delivery fee",
    "settings.serviceFee": "Service fee",
    "settings.saved": "Settings saved",
    "settings.pricing": "Pricing",
    "settings.deliveryFeeDesc": "Applied to every order at checkout",
    "notify.title": "Send Notification",
    "notify.type": "Type",
    "notify.notifTitle": "Title",
    "notify.message": "Message",
    "notify.audience": "Audience",
    "notify.allUsers": "All users",
    "notify.send": "Send",
    "notify.sent": "Sent to {n} users",
    "notify.required": "Title and message are required",
    "notify.howItWorks": "How it works",
    "notify.hint1": "Notification is sent to all non-blocked users",
    "notify.hint2": "Users see it in their Notifications tab in the client app",
    "notify.hint3": "Choose the right type: Info, Promo, System, or Order update",
    "promo.percent": "Percentage (%)",
    "promo.fixed": "Fixed amount (sum)",
    "orders.orderDetails": "Order details",
    "orders.payment": "Payment",
    "orders.delivery": "Delivery",
    "orders.contact": "Contact",
    "orders.subtotal": "Subtotal",
    "orders.deliveryFee": "Delivery fee",
    "orders.serviceFee": "Service fee",
    "orders.discount": "Discount",
    "orders.total": "Total",
    "orders.notes": "Notes",
    "orders.deliveryAddress": "Delivery address",
    "orders.items": "Items",
    "orders.maps": "Maps",
    "filter.all": "All",
    "orders.noOrders": "No orders found",
  },
  ru: {
    "nav.dashboard": "Дашборд",
    "nav.orders": "Заказы",
    "nav.products": "Товары",
    "nav.categories": "Категории",
    "nav.users": "Пользователи",
    "nav.promoCodes": "Промокоды",
    "nav.settings": "Настройки",
    "nav.notifications": "Уведомления",
    "common.save": "Сохранить",
    "common.cancel": "Отмена",
    "common.delete": "Удалить",
    "common.edit": "Изменить",
    "common.add": "Добавить",
    "common.active": "Активен",
    "common.inactive": "Неактивен",
    "common.search": "Поиск...",
    "common.loading": "Загрузка...",
    "common.noData": "Нет данных",
    "common.actions": "Действия",
    "common.block": "Заблокировать",
    "common.unblock": "Разблокировать",
    "common.signOut": "Выйти",
    "auth.signIn": "Войти",
    "auth.signInToAccount": "Войдите в аккаунт администратора",
    "products.title": "Товары",
    "products.add": "Добавить товар",
    "products.name": "Название",
    "products.category": "Категория",
    "products.type": "Тип",
    "products.series": "Серия",
    "products.variants": "Варианты",
    "products.sku": "Артикул",
    "products.flavor": "Вкус",
    "products.weight": "Вес",
    "products.price": "Цена",
    "products.stock": "Остаток",
    "products.image": "Изображение",
    "products.translations": "Переводы",
    "products.flavorLabel": "Название вкуса",
    "products.typeName": "Тип продукта",
    "products.description": "Описание",
    "products.ingredients": "Состав",
    "settings.title": "Настройки",
    "settings.deliveryFee": "Стоимость доставки",
    "settings.serviceFee": "Сервисный сбор",
    "settings.saved": "Настройки сохранены",
    "settings.pricing": "Цены",
    "settings.deliveryFeeDesc": "Применяется к каждому заказу при оформлении",
    "notify.title": "Отправить уведомление",
    "notify.type": "Тип",
    "notify.notifTitle": "Заголовок",
    "notify.message": "Сообщение",
    "notify.audience": "Аудитория",
    "notify.allUsers": "Все пользователи",
    "notify.send": "Отправить",
    "notify.sent": "Отправлено {n} пользователям",
    "notify.required": "Заголовок и сообщение обязательны",
    "notify.howItWorks": "Как это работает",
    "notify.hint1": "Уведомление отправляется всем незаблокированным пользователям",
    "notify.hint2": "Пользователи видят его во вкладке Уведомлений в клиентском приложении",
    "notify.hint3": "Выберите правильный тип: Инфо, Промо, Системное или Обновление заказа",
    "promo.percent": "Процент (%)",
    "promo.fixed": "Фиксированная сумма",
  },
  uz: {
    "nav.dashboard": "Boshqaruv",
    "nav.orders": "Buyurtmalar",
    "nav.products": "Mahsulotlar",
    "nav.categories": "Kategoriyalar",
    "nav.users": "Foydalanuvchilar",
    "nav.promoCodes": "Promo kodlar",
    "nav.settings": "Sozlamalar",
    "nav.notifications": "Bildirishnomalar",
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.delete": "O'chirish",
    "common.edit": "Tahrirlash",
    "common.add": "Qo'shish",
    "common.active": "Faol",
    "common.inactive": "Nofaol",
    "common.search": "Qidirish...",
    "common.loading": "Yuklanmoqda...",
    "common.noData": "Ma'lumot yo'q",
    "common.actions": "Amallar",
    "common.signOut": "Chiqish",
    "auth.signIn": "Kirish",
    "auth.signInToAccount": "Admin hisobingizga kiring",
    "products.title": "Mahsulotlar",
    "products.add": "Mahsulot qo'shish",
    "products.name": "Nomi",
    "products.category": "Kategoriya",
    "products.type": "Turi",
    "products.series": "Seriya",
    "products.variants": "Variantlar",
    "products.sku": "SKU",
    "products.flavor": "Ta'm",
    "products.weight": "Vazn",
    "products.price": "Narx",
    "products.stock": "Qoldiq",
    "products.image": "Rasm",
    "products.translations": "Tarjimalar",
    "products.flavorLabel": "Ta'm nomi",
    "products.typeName": "Mahsulot turi",
    "products.description": "Tavsif",
    "products.ingredients": "Tarkibi",
    "settings.title": "Sozlamalar",
    "settings.deliveryFee": "Yetkazib berish narxi",
    "settings.serviceFee": "Xizmat haqi",
    "settings.saved": "Sozlamalar saqlandi",
    "settings.pricing": "Narxlar",
    "settings.deliveryFeeDesc": "Har bir buyurtmada qo'llaniladi",
    "notify.title": "Bildirishnoma yuborish",
    "notify.type": "Turi",
    "notify.notifTitle": "Sarlavha",
    "notify.message": "Xabar",
    "notify.audience": "Auditoriya",
    "notify.allUsers": "Barcha foydalanuvchilar",
    "notify.send": "Yuborish",
    "notify.sent": "{n} ta foydalanuvchiga yuborildi",
  },
};

interface AdminLangState {
  lang: AdminLang;
  setLang: (l: AdminLang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const useAdminLangStore = create<AdminLangState>()(
  persist(
    (set, get) => ({
      lang: "en",
      setLang: (lang) => set({ lang }),
      t: (key, vars) => {
        const { lang } = get();
        let val = dict[lang]?.[key] ?? dict["en"]?.[key] ?? key;
        if (vars) {
          for (const [k, v] of Object.entries(vars)) {
            val = val.replace(`{${k}}`, String(v));
          }
        }
        return val;
      },
    }),
    { name: "admin-lang", storage: createJSONStorage(() => localStorage) }
  )
);

export default useAdminLangStore;
